stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - build
  image: node:12.14.1
  only:
      - master
  artifacts:
    untracked: true
    exclude:
      - "node_modules/"
  cache:
    paths:
      - node_modules/
  script:
    - echo "Compiling the code..."
    - export NODE_OPTIONS="--max-old-space-size=1024"
    - npm install
    - npm run build
    - echo "Compile complete."



deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  tags:
    - deploy
  only:
    - master
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  dependencies:
    - build-job
  script:
    - echo "Deploying application..."

    - docker stop $CI_PROJECT_NAME || true
    - docker rm $CI_PROJECT_NAME || true
    - docker run --name $CI_PROJECT_NAME -d
        -p 5321:80 --restart unless-stopped
        -v "$(pwd)"/dist:/usr/share/nginx/html
        nginx:latest
    - mv dist html
    - docker cp ./html $CI_PROJECT_NAME:/usr/share/nginx/
    - docker cp ./default.conf $CI_PROJECT_NAME:/etc/nginx/conf.d/default.conf
    - docker exec $CI_PROJECT_NAME sh -c "nginx -s reload"
    - echo "Application successfully deployed."